
server:
  port: 8889

spring:
  profiles:
    active: jdbc
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none
  cloud:
    config:
      server:
        jdbc:
          enabled: true
          sql: 'SELECT `key`, `value` FROM properties WHERE application = ? AND profile = ? AND label = ?'
          order: 1
